### PR TITLE
added missing *,/ operator for float

### PR DESCRIPTION
**Pull request by mbutaru**
It was causing problems when rendering images on screens with pixel ratio above 1.

### CODE REVIEW

**Comment by wjakob** [comment]
I think this is fixed by https://github.com/mitsuba-renderer/nanogui/commit/52772c03faced13accbde4ebb2e08414b34b8bbc, can you check? I would prefer not to touch the Array classes.

**Comment by mbutaru** [comment]
Hi,

I can't see how it can be fixed by that commit since there's no * operator
defined for a "single" float value.

Best regards,
Mihai

**Comment by wjakob** [comment]
What this commit does is to avoid an implicit cast by casting explicitly to a floating point representation. Could you please check it?

**Comment by wjakob** [comment]
Closing (no feedback/response to previous requests)

**Pull request closed without merging**
