### PR TITLE
Fix static GLFW dependencies on Linux/BSD

### PR DESCRIPTION
**Pull request by cyclopsian**
Potential fix for #13

### CODE REVIEW

**Comment by wjakob** [comment]
Shall I merge this? Is the fix confirmed? (I am working towards a deadline and unfortunately don't have the time to check myself..). 

Note also some complaints by other users: https://github.com/mitsuba-renderer/nanogui/issues/15

Perhaps it is better to just roll back the last commit?

**Comment by cyclopsian** [comment]
If time is sensitive then I would favor a revert until it is fully tested. I don't have a way to test on windows at the moment.

**Comment by wjakob** [comment]
ok, done.

**Comment by cyclopsian** [comment]
I am closing this to resubmit another PR with the collected fixes.

**Pull request closed without merging**
